AZEShop/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AZEShop.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace AZEShop.Controllers
{
    public class CartController : Controller
    {
        private readonly AZEShopDbContext context;

        public CartController(AZEShopDbContext context)
        {
            this.context = context;
        }

        public IActionResult Add(int id)
        {
            List<Product> cart = null;
            if (HttpContext.Session.Keys.Contains("cart"))
            {
                try
                {
                    var cartJson = HttpContext.Session.GetString("cart");
                    cart = JsonConvert.DeserializeObject<List<Product>>(cartJson);
                }
                catch (Exception)
                {
                    cart = new List<Product>();
                }
            }
            else
            {
                cart = new List<Product>();
            }

            var product = context
                .Products
                .FirstOrDefault(x => x.Id == id);

            cart.Add(product);

            var json = JsonConvert.SerializeObject(cart);
            HttpContext.Session.SetString("cart", json);

            return RedirectToAction("Index", "Home");
        }

        public IActionResult Remove(int id)
        {
            if (HttpContext.Session.Keys.Contains("cart"))
            {
                var cartJson = HttpContext.Session.GetString("cart");
                var cart = JsonConvert.DeserializeObject<List<Product>>(cartJson);
                cart.RemoveAll(x => x.Id == id);
                var json = JsonConvert.SerializeObject(cart);
                HttpContext.Session.SetString("cart", json);
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

AZEShop/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AZEShop.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace AZEShop.Controllers
{
    public class OrderController : Controller
    {
        private readonly AZEShopDbContext context;

        public OrderController(AZEShopDbContext context)
        {
            this.context = context;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Order order)
        {
            order = context.Orders.Add(order).Entity;
            context.SaveChanges();

            List<Product> products = JsonConvert.DeserializeObject<List<Product>>(HttpContext.Session.GetString("cart"));
            foreach (var item in products)
            {
                context.OrderProduct.Add(new OrderProduct { OrderId = order.Id, ProductId = item.Id });
            }
            context.SaveChanges();

            HttpContext.Session.Remove("cart");

            return RedirectToAction("Index", "Home");
        }
    }
}

AZEShop/Views/Shared/Components/Cart/Default.cshtml
@model IEnumerable<Product>

<button type="button" class="btn btn-success" data-toggle="modal" data-target="#cartModal">
    Your cart: @ViewBag.Cart
</button>


<div class="modal fade" id="cartModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">My cart: </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @if (Model != null)
                {
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col">Price</th>
                                <th scope="col">Delete</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Name</td>
                                    <td>@item.Price</td>
                                    <td><a asp-controller="Cart" asp-action="Remove" asp-route-id="@item.Id"><i class="fas fa-trash-alt text-danger"></i></a></td>
                                </tr>
                            }

                        </tbody>
                    </table>
                    <h2>Total: $@Model.Sum(x => x.Price)</h2>
                }
                else
                {
                    <p>Your cart is empty!</p>
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a asp-controller="Order" asp-action="Create" class="btn btn-primary">Order</a>
            </div>
        </div>
    </div>
</div>